# Generated by Django 5.1.1 on 2024-09-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('director', models.CharField(max_length=100)),
                ('actor_1', models.CharField(max_length=100)),
                ('actor_2', models.CharField(max_length=100)),
                ('actor_3', models.CharField(max_length=100)),
                ('actor_4', models.CharField(max_length=100)),
                ('year_of_release', models.IntegerField()),
                ('thump', models.ImageField(blank=True, default='default.png', upload_to='')),
            ],
        ),
    ]
